// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQAAGwjQh9sgPij6j7MUfwrTuPSYxaW4',
    appId: '1:651915310429:web:3cd9b251777e4537bea4b4',
    messagingSenderId: '651915310429',
    projectId: 'to-do-list-app-a5bbd',
    authDomain: 'to-do-list-app-a5bbd.firebaseapp.com',
    storageBucket: 'to-do-list-app-a5bbd.firebasestorage.app',
    measurementId: 'G-6RBN1F6D0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWR8H8gkMQXIzybI5_C54vzKPYm2aubDY',
    appId: '1:651915310429:android:63aed605020e430ebea4b4',
    messagingSenderId: '651915310429',
    projectId: 'to-do-list-app-a5bbd',
    storageBucket: 'to-do-list-app-a5bbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4XZXTBKE1c8FUPNWn9Q_N0aN3yyYjgE',
    appId: '1:651915310429:ios:b4da96b98a38dab0bea4b4',
    messagingSenderId: '651915310429',
    projectId: 'to-do-list-app-a5bbd',
    storageBucket: 'to-do-list-app-a5bbd.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD4XZXTBKE1c8FUPNWn9Q_N0aN3yyYjgE',
    appId: '1:651915310429:ios:b4da96b98a38dab0bea4b4',
    messagingSenderId: '651915310429',
    projectId: 'to-do-list-app-a5bbd',
    storageBucket: 'to-do-list-app-a5bbd.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdQAAGwjQh9sgPij6j7MUfwrTuPSYxaW4',
    appId: '1:651915310429:web:86babc04940588fbbea4b4',
    messagingSenderId: '651915310429',
    projectId: 'to-do-list-app-a5bbd',
    authDomain: 'to-do-list-app-a5bbd.firebaseapp.com',
    storageBucket: 'to-do-list-app-a5bbd.firebasestorage.app',
    measurementId: 'G-6RPTG9RM7E',
  );

}